'use strict';

var config = require('./gulp.config')();
var del = require('del');
var merge = require('merge2');
var stream = require('event-stream');
var args = require('yargs').argv;
var browserSync = require('browser-sync');
var gulp = require('gulp');
var $ = require('gulp-load-plugins')({ lazy: true });

/**
 * yargs variables can be passed in to alter the behavior, when present.
 * Example: gulp typescript-compile
 *
 * --verbose  : Various tasks will produce more output to the console.
 * --clean    : Delete generated files
 */

/**
 * List the available gulp tasks
 */
gulp.task('help', $.taskListing.withFilters(/:/));
gulp.task('default', ['help']);

/**
 * Compile TypeScript
 */
gulp.task('typescript-compile', function () {
    
    if (args.clean) {
        cleanTypeScript();
    };

    log('Compiling TypeScript')
    
    var tsResult = gulp.src(config.ts.files)
        .pipe($.sourcemaps.init())
        .pipe($.typescript({
            module: config.ts.compilerOptions.module,
            target: config.ts.compilerOptions.target,
            noImplicitAny: config.ts.compilerOptions.noImplicitAny,
            declaration: config.ts.compilerOptions.declaration
        }));
        
    return stream.merge(
        tsResult.dts.pipe(gulp.dest(config.ts.typings)),
        tsResult.js
            .pipe($.sourcemaps.write('.'))
            .pipe(gulp.dest(config.ts.out)));
});

/**
 * Watch and compile TypeScript
 */
gulp.task('typescript-watch', function () {
    
    return gulp.watch(config.ts.files, ['typescript-compile']);
});

/**
 * Run specs once and exit
 * @return {Stream}
 */
gulp.task('tests-run', function () {
    
    startTests(true /*singleRun*/);
});

/**
 * Run specs and wait.
 * Watch for file changes and re-run tests on each change
 */
gulp.task('tests-watch', ['typescript-watch'], function () {
    
    startTests(false /*singleRun*/);
});

/**
 * Inject all the spec files into the SpecRunner.html
 * @return {Stream}
 */
gulp.task('specs:inject', function () {
    
    log('injecting scripts into the spec runner');

    return gulp
        .src(config.specRunner)
        .pipe(inject(config.js.src, '', config.js.order))
        .pipe(inject(config.js.specs, 'specs', ['**/*']))
        .pipe(gulp.dest(config.root));
});

/**
 * Run the spec runner
 * @return {Stream}
 */
gulp.task('tests-serve', ['specs:inject', 'typescript-watch'], function () {
    
    log('run the spec runner');
    serveSpecRunner();
});

////////////////

/**
 * Log a message or series of messages using chalk's blue color.
 * Can pass in a string, object or array.
 */
function log(msg) {
    
    if (typeof (msg) === 'object') {
        for (var item in msg) {
            if (msg.hasOwnProperty(item)) {
                $.util.log($.util.colors.blue(msg[item]));
            }
        }
    } else {
        $.util.log($.util.colors.blue(msg));
    }
}

/**
 * Remove all files generated by the TypeScript compiler
 * @param  {Array}   path - array of paths to delete
 */
function cleanTypeScript() {
    
    var delconfig = [].concat(config.ts.outFiles);
    log('Cleaning TypeScript generated files: ' + $.util.colors.blue(delconfig));
    return del(delconfig);
}

/**
 * Delete all files in a given path
 * @param  {Array}   path - array of paths to delete
 */
function clean(path) {
    
    log('Cleaning: ' + $.util.colors.blue(path));
    return del(path);
}

/**
 * Start the tests using karma.
 * @param  {boolean} singleRun - True means run once and end (CI), or keep running (dev)
 * @return {undefined}
 */
function startTests(singleRun) {

    var Server = require('karma').Server;

    log('Karma started');

    var server = new Server({
        configFile: __dirname + '/karma.conf.js',
        exclude: config.karma.exclude,
        singleRun: !!singleRun
    });

    server.on('run_complete', function (browser, result) {
        log('Karma completed');
    });

    server.start();
}

/**
 * Order a stream
 * @param   {Stream} src   The gulp.src stream
 * @param   {Array} order Glob array pattern
 * @returns {Stream} The ordered stream
 */
function orderSrc(src, order) {
    
    return gulp
        .src(src)
        .pipe($.if(order, $.order(order)));
}

/**
 * Inject files in a sorted sequence at a specified inject label
 * @param   {Array} src   glob pattern for source files
 * @param   {String} label   The label name
 * @param   {Array} order   glob pattern for sort order of the files
 * @returns {Stream}   The stream
 */
function inject(src, label, order) {
    
    var options = { read: false, addRootSlash: false };
    if (label) {
        options.name = 'inject:' + label;
    }
    return $.inject(orderSrc(src, order), options);
}

/**
 * Start BrowserSync
 */
function serveSpecRunner() {
    
    if (browserSync.active) {
        return;
    }

    log('Starting BrowserSync on port ' + config.browserSyncPort);

    var options = {
        port: config.browserSync.port,
        server: config.root,
        files: config.js.srcSpecs,
        logFileChanges: true,
        logLevel: config.browserSync.logLevel,
        logPrefix: config.browserSync.logPrefix,
        notify: true,
        reloadDelay: config.browserSync.reloadDelay,
        startPath: config.specRunnerFile
    };
    
    if (args.verbose) {
        options.logLevel = 'debug';
    }

    browserSync(options);
}
